package ir.rhinocloud.easyotp.net

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The device half of the identifier chain, plus the fixture the Worker checks it
 * against.
 *
 * A mismatch here does not throw. Enrolment reports success, the webhook is
 * registered under an id the device cannot derive, and nothing is ever delivered
 * -- so this is verified across languages rather than asserted on one side.
 */
class ChannelIdsTest {

    /** Fixed input so the derivation is reproducible on both sides. */
    private val channelId = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8"

    @Test
    fun `derivation is deterministic`() {
        // The relay recomputes on every request rather than storing a mapping,
        // so a non-deterministic derivation would break authorisation outright.
        assertEquals(
            ChannelIds.secretTokenFrom(channelId),
            ChannelIds.secretTokenFrom(channelId),
        )
    }

    @Test
    fun `each link produces a distinct value`() {
        val secret = ChannelIds.secretTokenFrom(channelId)
        val webhook = ChannelIds.webhookIdFrom(secret)
        assertNotEquals(channelId, secret)
        assertNotEquals(secret, webhook)
        assertNotEquals(channelId, webhook)
    }

    @Test
    fun `identifiers are 32 bytes, url-safe and unpadded`() {
        // They travel in URLs and in an HTTP header; padding or a slash would be
        // mangled somewhere along the path.
        val webhook = ChannelIds.webhookIdForChannel(channelId)
        assertEquals(43, webhook.length)
        assertTrue(webhook.none { it == '+' || it == '/' || it == '=' })
    }

    @Test
    fun `domain separation makes the two links differ`() {
        // Without distinct domains, a value valid at one position would be valid
        // at another, and Telegram's secret token would drain the mailbox.
        val same = RelaySealer.base64UrlDecode(channelId)
        assertNotEquals(
            ChannelIds.secretTokenFrom(channelId),
            ChannelIds.webhookIdFrom(RelaySealer.base64UrlEncode(same)),
        )
    }

    @Test
    fun `generated channel ids are unique and full length`() {
        val a = ChannelIds.newChannelId()
        val b = ChannelIds.newChannelId()
        assertNotEquals(a, b)
        assertEquals(32, RelaySealer.base64UrlDecode(a).size)
    }

    /** Writes the fixture worker/test/interop.spec.ts compares against. */
    @Test
    fun `emit id chain fixture`() {
        val secret = ChannelIds.secretTokenFrom(channelId)
        val webhook = ChannelIds.webhookIdFrom(secret)
        val json = """
            {
              "note": "Generated by ChannelIdsTest. Regenerate: ./dev build testDebugUnitTest",
              "channelId": "$channelId",
              "secretToken": "$secret",
              "webhookId": "$webhook"
            }
        """.trimIndent()

        val out = File(System.getProperty("easyotp.fixtureDir") ?: "build/interop")
        out.mkdirs()
        File(out, "ids-fixture.json").writeText(json + "\n")
    }
}
