package ir.rhinocloud.easyotp.net

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Sealing, plus generation of the cross-language interop fixture.
 *
 * The fixture is the point. Tink and hpke-js can both be individually correct and
 * still fail to interoperate over settings that produce no useful error -- the
 * Tink key-id prefix, or a mismatched HPKE `info`. Only an envelope produced by
 * one and opened by the other proves it, so this test writes one and
 * worker/test/interop.spec.ts consumes it.
 */
class RelaySealerTest {

    /** Public half of worker/test/interop-keys.ts. Test-only, valid nowhere. */
    private val relayPublicKey = "cPBUlcXX9VZOze4ZSgxhSk3rUs3a1w92okcGQO2Xk04"

    private val sealer = RelaySealer.fromBase64Url(relayPublicKey)

    @Test
    fun `encapsulated key is exactly one X25519 public key`() {
        // The relay splits the Tink output at a fixed offset, so a suite change
        // that alters this length would corrupt every envelope silently.
        val sealed = sealer.seal("hello".toByteArray())
        assertEquals(32, sealed.enc.size)
        assertTrue(sealed.ciphertext.isNotEmpty())
    }

    @Test
    fun `sealing twice never repeats an envelope`() {
        // HPKE picks a fresh ephemeral key per seal. Identical output would mean
        // a static sender key, making every message correlatable on the wire.
        val a = sealer.seal("same plaintext".toByteArray())
        val b = sealer.seal("same plaintext".toByteArray())
        assertNotEquals(a, b)
        assertFalse(a.enc.contentEquals(b.enc))
    }

    @Test
    fun `a wrong-sized relay key is rejected at construction`() {
        // Better to fail at startup than to ship envelopes nothing can open.
        val error = runCatching { RelaySealer(ByteArray(31)) }.exceptionOrNull()
        assertTrue(error is IllegalArgumentException)
    }

    @Test
    fun `base64url round-trips without padding`() {
        val bytes = ByteArray(32) { it.toByte() }
        val encoded = RelaySealer.base64UrlEncode(bytes)
        assertTrue("must be url-safe", !encoded.contains('+') && !encoded.contains('/'))
        assertTrue("must be unpadded", !encoded.contains('='))
        assertTrue(bytes.contentEquals(RelaySealer.base64UrlDecode(encoded)))
    }

    /**
     * Writes the fixture the Worker test opens.
     *
     * Not an assertion so much as a generator: the real verification happens in
     * worker/test/interop.spec.ts, which fails if this envelope cannot be opened
     * with the matching private key.
     */
    @Test
    fun `emit interop fixture`() {
        val plaintext = INTEROP_PLAINTEXT.toByteArray()
        val sealed = sealer.seal(plaintext)

        val json = """
            {
              "note": "Generated by RelaySealerTest. Regenerate with: ./dev build testDebugUnitTest",
              "publicKey": "$relayPublicKey",
              "plaintext": ${quote(INTEROP_PLAINTEXT)},
              "enc": "${RelaySealer.base64UrlEncode(sealed.enc)}",
              "ct": "${RelaySealer.base64UrlEncode(sealed.ciphertext)}"
            }
        """.trimIndent()

        val out = File(System.getProperty("easyotp.fixtureDir") ?: "build/interop")
        out.mkdirs()
        File(out, "hpke-fixture.json").writeText(json + "\n")
        println("INTEROP_FIXTURE_BEGIN$json" + "INTEROP_FIXTURE_END")
    }

    private fun quote(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    private fun assertFalse(condition: Boolean) = assertTrue(!condition)

    private companion object {
        /** Shaped like a real forward payload so the fixture exercises realistic input. */
        const val INTEROP_PLAINTEXT =
            """{"botToken":"123456:TEST","chatId":42,"text":"Your code is <code>4821</code>"}"""
    }
}
