package ir.rhinocloud.easyotp.data

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM sealing against a key that never leaves the Android Keystore.
 *
 * Used for message payloads at rest (DECISIONS D13) and for stored credentials.
 * The key is generated on the device, is non-exportable, and is hardware-backed
 * wherever the device offers it -- so copying the database off the device yields
 * blobs and nothing else.
 *
 * Deliberately not `androidx.security:security-crypto`: that library has been
 * through deprecation churn, and this is sixty lines of platform API. For an app
 * whose whole claim is auditability, a reviewer being able to read the entire
 * at-rest crypto path in one sitting is worth more than the dependency.
 */
class KeyVault(private val alias: String = DEFAULT_ALIAS) {

    /** IV ‖ ciphertext ‖ tag. The IV is generated by the provider, never reused. */
    fun seal(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val iv = cipher.iv
        require(iv.size == IV_BYTES) { "unexpected GCM IV length ${iv.size}" }
        return iv + cipher.doFinal(plaintext)
    }

    fun open(sealed: ByteArray): ByteArray {
        require(sealed.size > IV_BYTES) { "sealed blob too short" }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            key(),
            GCMParameterSpec(TAG_BITS, sealed, 0, IV_BYTES),
        )
        return cipher.doFinal(sealed, IV_BYTES, sealed.size - IV_BYTES)
    }

    private fun key(): SecretKey {
        val store = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (store.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        return generate()
    }

    private fun generate(): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            // No user-authentication requirement: the capture path runs from a
            // broadcast receiver while the phone sits unattended in another
            // country. A key that needs the screen unlocked would drop every
            // message the product exists to deliver.
            .setRandomizedEncryptionRequired(true)
            .apply {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    // Discrete security chip when present. Silently ignored on
                    // devices without one, so no version fork beyond this.
                    setIsStrongBoxBacked(true)
                }
            }
            .build()

        return try {
            generator.init(spec)
            generator.generateKey()
        } catch (e: Exception) {
            // StrongBox is advertised inconsistently across OEMs and throws at
            // generation time rather than at query time. Fall back to the TEE.
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.P) throw e
            val fallback = KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setRandomizedEncryptionRequired(true)
                .build()
            generator.init(fallback)
            generator.generateKey()
        }
    }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val DEFAULT_ALIAS = "easyotp.payload.v1"
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}
