// Test-only HPKE keypair for the Android<->Worker interop fixture.
// Generated by worker/scripts/keygen.mjs; valid nowhere else. The Android unit
// test seals to the public half, and interop.spec.ts unseals with the private
// half -- so a change to either side's crypto settings fails CI rather than
// silently producing envelopes the relay cannot open.
export const INTEROP_PRIVATE_KEY = "oM36R01IPG6RZUUybmE_TX_G7E6m5mfLCeeSvuU9pn0";
export const INTEROP_PUBLIC_KEY = "cPBUlcXX9VZOze4ZSgxhSk3rUs3a1w92okcGQO2Xk04";
